### ISSUE TITLE
Booth capable of operating more than one set of clusters?

### ISSUE THREAD

**Issue by jfriesse** [ClusterLabs/booth#108]
Hi,
I've got following https://bugzilla.redhat.com/show_bug.cgi?id=1986308 report.

Main idea (if I understand it correctly) is to support booth arbitrator to arbitrate multiple set of clusters. IMHO it doesn't make too much sense (or actually it makes no sense because booth itself creates cluster membership), but I would like to see more opinions (or maybe it's already implemented?)

I think current ability to run multiple booth daemons is more than viable alternative ("workaround").

**Comment by dmuhamedagic** [comment]
Yes, it would be preferable to simply run multiple instances of
booth. booth is easy on all resources (mem, cpu, disk). Off the
top of my head, I'm not sure if it is possible, but should be
easy to implement.

**Comment by jfriesse** [comment]
Thank you for the confirmation. There is now article how to make multiple booth instancies setup work (https://access.redhat.com/solutions/6215711) so closing this issue.
