### ISSUE TITLE
booth: Got a site-ID collision

### ISSUE THREAD

**Issue by djurdjura** [ClusterLabs/booth#55]
While restarting the booth arbitrator, I got the following error:

Mar 28 08:28:56 Vlab20Node1 booth: [29795]: ERROR:
Got a site-ID collision. Please file a bug on
https://github.com/ClusterLabs/booth/issues/new, attaching the configuration file.

$ boothd --version
boothd 0.2.0 (build v0.2.0-6-g9eae45f)

$ uname -a
Linux Vlab20Node1 3.0.101-94-default #1 SMP Thu Jan 26 12:20:59 UTC 2017 (c499ea8) x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 4

The booth configuration file:
===============================
transport="UDP"

port="9929"

arbitrator="10.150.20.132"

site="10.150.20.144"
site="10.150.20.144"

ticket="geo-ticket"
        expire=300
=============================

**Comment by dmuhamedagic** [comment]
> The booth configuration file:
> ===============================
> transport="UDP"
> 
> port="9929"
> 
> arbitrator="10.150.20.132"
> 
> site="10.150.20.144"
> site="10.150.20.144"

You cannot have two sites with identical IPs.

**Comment by dmuhamedagic** [comment]
Incorrect configuration. Closing.
