### ISSUE TITLE
Introduce manual tickets for 2-site clusters

### ISSUE THREAD

**Issue by ChrisKowalczyk** [ClusterLabs/booth#60]
# Goal 
Many customers would like to have a possibility to set up 2-site Booth clusters. So, we would like to allow them to create a cluster without an arbitrator.
In such a case, the problem could arise if one site broke down or the communication was corrupted, because we would lose quorum. Therefore, we it wouldn't be possible for an administrator to grant a ticket to any site.

# Proposed Solution
The idea would be to create a new ticket attribute, 'manual mode'.
In a manual mode, if both sites are online, Booth could still ensure a ticket is granted to only one site at a time.
In case one site is down/lost or split-brain occurs, an administrator can decide to bypass the requirement of the quorum and manually grant a ticket to the considered healthy site, which basically enforces manual failover. It also means that the users are on their own for this: they have to make sure by themselves that this ticket hasn't been already granted to another site at the same time.

## Manual Tickets' Behavior
The idea would be to disable election for 'manual tickets' and, similarly, to disable expiration time for them. If a manual ticket was granted to a site, other sites would not try to deal with it. Also, after 'booth grant' command, the site would only notify other nodes about acquiring the ticket.

## Artificial Arbitrator
Another way to solve this issue would be to introduce some kind of 'fake'/'artificial' arbitrator, which would automatically add its vote when granting a ticket in a manual mode.

# Discussion
Could you let me know what do you think about this? And any other comments you may have regarding the idea and the implementation? Any comments are warmly welcomed!

**Comment by dmuhamedagic** [comment]
This sounds similar to a cluster with the meatware stonith
agent, right? Perhaps it would be good to consider that: a site
fencing implementation. Fencing is a concept that's well
understood and, furthermore, building such an infrastructure may
be of benefit itself.

Running an arbitrator is rather cheap. In particular when
compared to running two sites and everything else included in
such a complex setup. I don't quite get it why would anybody want
to do this. Or is there another, non-monetary reason?

**Comment by gao-yan** [comment]
I think the main point is the "manual mode" for ticket. Many "potential" users think failover is big move. They don't want that to be done automatically...

Of course they could either do that purely manually with crm_ticket. But with booth, it'd still be able to prevent a ticket from being granted to more than one online site by mistake/accident.

So basically the  per-ticket "manual mode" would meet the use case for geo clusters with any amounts of sites.

Meanwhile, considering an arbitrator for 2-site geo-cluster needs to be at a third location, there could be difficulty for the users although the node itself might be cheap. But with such a "manual mode", an arbitrator would no longer be needed. 2-site geo-cluster in "manual mode" could open the doors for more users.

**Comment by ChrisKowalczyk** [comment]
I agree that _manual mode_ is not the only possible solution, however as gao-yan wrote above, this was a kind of behavior some users would expect. I think they would like to be able to bind certain resources to a specific geo-sites. In this case, they would not be keen to bother with arbitrators at all.
I would also agree that such a _manual mode_ would be a different behavior than a typical HA approach, and this is a drawback. However, if we keep clear separation between _normal_ and _manual_ tickets (in the code and _documentation_), I hope we could add a new value to Booth, without harming its main functionality.

**Comment by dmuhamedagic** [comment]
On Wed, Jul 05, 2017 at 03:28:22PM +0000, Gao,Yan wrote:
> I think the main point is the "manual mode" for ticket. Many "potential" users think failover is big move. They don't want that to be done automatically...

Yes, I can understand that.

> Of course they could either do that purely manually with crm_ticket. But with booth, it'd still be able to prevent a ticket from being granted to more than one online site by mistake/accident.
> 
> So basically the  per-ticket "manual mode" would meet the use case for geo clusters with any amounts of sites.
> 
> Meanwhile, considering an arbitrator for 2-site geo-cluster needs to be at a third location, there could be difficulty for the users although the node itself might be cheap. But with such a "manual mode", an arbitrator would no longer be needed. 2-site geo-cluster in "manual mode" could open the doors for more users.

OK. This is then basically the case where the consensus algorithm
is out of picture and booth is used just to manage the tickets.
Perhaps even a different binary name would then be preferable?

**Comment by dmuhamedagic** [comment]
Agreed. Note that booth, unless in case of quorum loss, doesn't
decide where tickets are granted, that is up to the
administrator. We just need to cleanly separate this "management"
mode from the "quorum" (HA) mode.

**Comment by gao-yan** [comment]
Thanks for the good thinking, Dejan.

I'm not sure if it's necessary to use a different binary name. Probably it's something for Chris to investigate too;-) But if it's feasible to make such a "manual mode" a per-ticket parameter, we would be able to manage both "automatic" tickets and "manual" ones at the same time in a same geo cluster...

The first grant is the same for the both types of tickets -- it has to be requested by administrator.

After that, as we know, an "automatic" ticket is taken care of by booth based on the consensus algorithm  and quorum -- the ticket automatically fails over if the holder is lost and the remaining sites have the quorum...

For a manual ticket, booth handles them only for the requests from administrator. It bypasses the consensus algorithm and quorum check. It only checks if the ticket is  already known to be granted to any of the current online sites...

Only my 2 cents:-)

**Comment by dmuhamedagic** [comment]
I also think that with this implementation one can most probably
run both kinds of tickets. Though that could be confusing and
would need to be thoroughly documented, with big red warning
signs :)

**Comment by gao-yan** [comment]
Agreed :-)  And it makes lot of sense to clearly indicate the tickets are either "automatic" or "manual" from the output of "booth list" and all the relevant log messages. And also reminders/warnings/prompts especially when granting tickets would be very helpful.

**Comment by ChrisKowalczyk** [comment]
Thanks, guys for all comments!
Do you have any preferences how to implement this codewise? Shouldn't manual-tickets start election at all? I believe that the timeout etc shouldn't apply to them as well?

**Comment by gao-yan** [comment]
I don't think a grant request for a manual-ticket should start an *election* in terms of consensus algorithm. I think it should simply bypasses that. But it has to check if the ticket is already granted to any of the online sites:

- If the ticket is not granted to any of the online sites:
  * If all the configured sites are online, grant the ticket immediately.
  * If there are any offline sites:
    ** By default, grant fails with a warning.
    ** With "-F", it grants the ticket with a warning like "the risk is on your own".

- If it's already granted to another online site:
  * By default, grant fails. It warns and tells user to manually revoke the ticket from the current holder first.
  * With "-F", it first revokes the ticket from the current holder, waits the time "acquire-after" and grants it.

Does it make sense? But probably there are thingg I'm missing here :-)

**Comment by dmuhamedagic** [comment]
I also think that managing manual tickets should not start or
influence elections in any way. Probably not even acquire-after:
we can do nothing but assume that they know what they're doing.

**Comment by gao-yan** [comment]
Given that it usually takes time to relinquish the resources after the ticket is revoked, it'd probably still be good to provide users this possibility to utilize such a delay. Of course they should omit it in the configuration if they don't need it ;-)

**Comment by ChrisKowalczyk** [comment]
Looking great, thanks guys for all the comments! So, just to summarize:
* we want to add **manual** attribute to tickets (.conf file)
* granting/revoking manual tickets shouldn't start elections
* a manual ticket shall never expire OR nodes should not check its expiration time
* before granting a manual ticket, the node shall check if it is already granted. If so, it will prevent granting this ticket.
* we will allow the user to set acquire-after time, and act accordingly.

One more question I can think of now. What shall we do if the node which used to have a manual ticket granted, became offline (the last response was long time ago), and we are trying to grant this ticket somewhere else. Should we consider this ticket to be already granted (and thus, prevent the action), or should we allow the user to grant it elsewhere? I would say, we could force the user to revoke it first, but maybe you have some objections?

**Comment by gao-yan** [comment]
Good question. I think in such a case:
* By default, grant fails. It warns and tells user that the lost site might still hold the ticket.
* With "-F", it grants the ticket with the same warning and also "the risk is on your own".

The interesting situation is, when the site rejoins and the ticket is indeed still granted there and now there are two sites holding the same ticket. Given that we already gave the warning, it's the administrators's fault ;-) We should give a RED warning and keep the situation. The administrator has to decide and run "booth revoke" with an option supplying which of the sites they want to revoke the ticket from.

**Comment by ChrisKowalczyk** [comment]
Generally, agreed. What about using some different command than 'booth revoke' for removing a ticket from a specific site. I mean, there would be many cases to handle: _revoke -s A_, when A doesn't exist, _revoke -s .._ for automatic tickets, _revoke -s A_, when A doesn't have a ticket but it is somewhere else, etc...
How about a command _booth revoke-manual sitename_ which would have a slightly different logic than _booth revoke_, and would focus on removing a ticket from the specified site (and would handle all those corner cases mentioned above)?

**Comment by gao-yan** [comment]
I'd try not to complicate the front-end interface. Besides it's not for an administrator to say if it's manual a ticket or not, although they have to know that ;-)

Of course the first thing for booth/boothd  to do is to identify if it's a manual ticket or not, and separate the two cases in the logic/code structure.

**Comment by dmuhamedagic** [comment]
On Fri, Jul 21, 2017 at 03:04:31AM -0700, Gao,Yan wrote:
> I'd try not to complicate the front-end interface. Besides it's not for an administrator to say if it's manual a ticket or not, although they have to know that ;-)
> 
> Of course the first thing for booth/boothd  to do is to identify if it's a manual ticket or not, and separate the two cases in the logic/code structure.

It seems to me too that the user interface doesn't need to change. The client and the server should take care of all the details regarding normal vs. manual tickets.

**Comment by dmuhamedagic** [comment]
This got merged. Closing.
