### ISSUE TITLE
Debug output in foregroud

### ISSUE THREAD

**Issue by ChrisKowalczyk** [ClusterLabs/booth#61]
Hello All,
Are there any reasons why we want to keep Booth working in a 'debug output' mode (-D) in the foreground?
Currently the parameter "-D" does two things: enable 'debug output' and moves Booth to the foreground. To make it run with resource agents in debug output mode, we need it run in the background.
Would you mind me adding another parameter for debug output + background operations? Or changing the behavior of -D flag? Do you have any preferences how it should be handled?
Regards,
Chris

**Comment by dmuhamedagic** [comment]
Runs in the foreground because the debugging output goes to
stderr. It is typical for many daemons to implement debugging
mode like that. Otherwise, I don't see any problem for the
ability to run in debugging mode in the background as well. Just
pick another option letter (it seems like 'd' is free).

**Comment by ChrisKowalczyk** [comment]
It works fine for me, thank you Dejan!
I will add '-d' option.

**Comment by ChrisKowalczyk** [comment]
Having second thoughts, wouldn't be more clear to limit -D option to just enable debugging and add another one (say, -F) which would move boothd to the foreground?
Otherwise, we will end up having two -D and -d, very similar though different options.

**Comment by dmuhamedagic** [comment]
There is an option to run booth in foreground (-S). Since it's
for debugging only, we can change the semantics and separate the
two (-S and -D).

**Comment by ChrisKowalczyk** [comment]
Merged to Master branch
