### ISSUE TITLE
Booth before-acquire-handler does not work

### ISSUE THREAD

**Issue by SupremeGit** [ClusterLabs/booth#79]
I am really angry.

before-acquire-handler does not work.

I have tried everything. I have a working booth setup, somehow, in spite of the poor documentation, but when i add before-acquire-handler it fails miserably. It looks like it is not even executing the script I have set. It just says that it fails, and when i try to grant a ticket, it is denied.

People are paying for this as part of Red Hat HA addon.

Why does it not work?
If it does not work, why is there no documentation saying that it does not work?
Why have I spent nearly a day trying to get it to work, when it is never going to work?

**Comment by jnpkrn** [comment]
Feel free to reopen this, @SupremeGit 

I am sorry about this situation that makes you think
`before-acquire-handler` does not work.

You haven't presented anything concrete about the problem
at hand, but I suspect you see the arguably counter-intuitive
behaviour that was introduced with asynchronous approach
to executing configured executable(s):

   - https://github.com/ClusterLabs/booth/commit/7c30fb4c8580f9784d75bc4dc27223c63491d3df
   - https://github.com/ClusterLabs/booth/commit/5575f95d032116c93d13eb84d71f80604ad6d90d

Could not find what triggered such a change, and it
does not appear detailed in documentation at an appropriate
level.

Anyway, if it's the timing whereby the script finishes (or is even
launched in some circumstances) way too late, after some
steps have already been deliberately taken regarding possession
of the ticket at hand, you can compensate for that time offset
with `acquire-after`.

Let's look at this constructively if you wish.

**Comment by dmuhamedagic** [comment]
On Wed, Jan 15, 2020 at 02:35:52PM -0800, Jan Pokorný wrote:
> Feel free to reopen this, @SupremeGit 
> 
> I am sorry about this situation that makes you think
> `before-acquire-handler` does not work.

Last time I looked it did work. It is also normally part of the
regression testing suite (i.e. live_test). We never release
without live_test passing.

> You haven't presented anything concrete about the problem
> at hand, but I suspect you see the arguably counter-intuitive
> behaviour that was introduced with asynchronous approach
> to executing configured executable(s):
> 
>    - https://github.com/ClusterLabs/booth/commit/7c30fb4c8580f9784d75bc4dc27223c63491d3df
>    - https://github.com/ClusterLabs/booth/commit/5575f95d032116c93d13eb84d71f80604ad6d90d
> 
> Could not find what triggered such a change, and it
> does not appear detailed in documentation at an appropriate
> level.

Before that change, the external program could block the boothd
process indefinitely which could essentially lead to a
split-brain condition. I'd say that that former behaviour was
rather counterintuitive. If you think this needs to be better
documented, please go ahead and do so.

> Anyway, if it's the timing whereby the script finishes (or is even
> launched in some circumstances) way too late, after some
> steps have already been deliberately taken regarding possession
> of the ticket at hand, you can compensate for that time offset
> with `acquire-after`.

boothd waits for the scripts to finish or runs into the timeout.
Either way, it won't go forward with ticket acquire/renewal, so
normally having to add such a time offset would mean that
something is buggy.

> Let's look at this constructively if you wish.

By all means. But we really need some information (logs and the
configuration).
